name: Contenedor Snyk

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '18 9 * * 3'  # Run every Wednesday at 09:18 UTC

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my/test-image .

      - name: Scan Docker image with Snyk
        continue-on-error: true
        uses: snyk/actions/docker@14818c4695ecc4045f33c9cee9e795a788711ca4
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: my/test-image
          args: --file=Dockerfile --sarif-file-output=snyk.sarif
          
      - name: Fix SARIF security-severity (results + rules)
        run: |
          jq '
            # Fix results[]
            (.runs[].results[]?.properties."security-severity") |=
              if . == null then "5.0" else . end
            |
            # Fix rules[]
            (.runs[].tool.driver.rules[]?.properties."security-severity") |=
              if . == null then "5.0" else . end
          ' snyk.sarif > fixed.sarif
          mv fixed.sarif snyk.sarif



      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

